services:
  viofo-pipeline:
    build: .
    image: ryanwayne/viofo-pipeline:latest
    container_name: viofo-pipeline
    env_file: .env
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./downloads:/app/downloads
      - /var/lib/dbus:/var/lib/dbus  # optional, for D-Bus control
      - /var/run/wpa_supplicant:/var/run/wpa_supplicant
      # - /mnt/dashcam/videos:/mnt/dashcam
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    restart: unless-stopped
